### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by isandeepkadam**

### CODE REVIEW

**Comment by shubham-cpp** [comment]
Looks good. 
Only question what about mobile view?

**Comment by isandeepkadam** [comment]
> Looks good. Only question what about mobile view?

Oh no, I didn't request a review because I still hadn't finished working on everything. I'll try to update it when it's done.

**Comment by shubham-cpp** [comment]
Ok, I've also pushed few changed

**Comment by shubham-cpp** [comment]
Also, instead of dropdown, I think [Sheet](https://ui.shadcn.com/docs/components/sheet) is better option

**Review by shubham-cpp — COMMENTED** [review]
Looks good.

TODO: Fix the Sheet not auto closing after selecting an item.
EG: On mobile, If I open the sheet and select Tags/Questions/Companies then it should autoclose the Sidebar

**Pull request merged**
